let projects = [
  {
    name: "Topological Data Analysis for COVID19 Data",
    sourceImage: "images/UPHESS_project1.jpeg",
    labels: ["docker", "topology", "python", "graph-theory", "web-app"],
    cut: 3,
    rel_width: "70%",
  },
  {
    name: "Topological Optimization Machine Learning",
    sourceImage: "images/UPHESS_project2.png",
    labels: ["topology", "multi-parameter", "metric", "smart-classifier"],
    cut: 2,
    rel_width: "70%",
  },
  {
    name: "Computing Levelset Zigzag Homology",
    sourceImage: "images/UPHESS_project3.png",
    labels: ["topology", "multi-parameter", "viz", "survey"],
    cut: 2,
    rel_width: "70%",
  },
  {
    name: "Applications of Discrete Morse Theory to Machine Learning",
    sourceImage: "images/UPHESS_project4.png",
    labels: ["topology", "python", "graph-theory", "geometry"],
    cut: 2,
    rel_width: "80%",
  },
  {
    name: "Data Visualization for SwissTopo Geolocation Data",
    sourceImage: "images/QH_project1bis.png",
    labels: ["finance", "real-estate", "viz", "postgreSQL"],
    cut: 2,
    rel_width: "86%",
  },
  {
    name: "Behavioral Data Imputer for MNAR-type Data ",
    sourceImage: "images/QH_project2.png",
    labels: ["imputation", "real-estate", "viz", "MNAR-data"],
    cut: 2,
    rel_width: "80%",
  },
  {
    name: "Financial Statistics for Real Estate Time-Series Data",
    sourceImage: "images/QH_project3.png",
    labels: ["imputation", "real-estate", "time-series", "postgreSQL"],
    cut: 2,
    rel_width: "80%",
  },
  {
    name: "Developing ESG Criteria for the Real Estate Market",
    sourceImage: "images/QH_project4.png",
    labels: ["environment", "real-estate", "ESG", "mobility"],
    cut: 2,
    rel_width: "80%",
  },
  {
    name: "Convolutional Neural Network Architecture for Road Segmentation",
    sourceImage: "images/EPFL_project1.png",
    labels: ["image-analysis", "neural-net", "segmentation", "pytorch"],
    cut: 2,
    rel_width: "60%",
  },
  {
    name: "Graph Theoretical Label Propagation for Image Classification",
    sourceImage: "images/EPFL_project2.png",
    labels: [
      "graph-theory",
      "discrete-laplacian",
      "smart-classifier",
      "propagation",
    ],
    cut: 2,
    rel_width: "80%",
  },
  {
    name: "Statistical Analysis for the Geneva Meteorological Observatory",
    sourceImage: "images/EPFL_project3.png",
    labels: ["web-app", "forecasting", "statistical-analysis", "viz"],
    cut: 2,
    rel_width: "60%",
  },
  {
    name: "Mathematical Modeling of Behavior for Urbanity and Mobility",
    sourceImage: "images/EPFL_project4.png",
    labels: ["statistical-ML", "forecasting", "behavior", "transport"],
    cut: 2,
    rel_width: "80%",
  },
];

export default projects;
